.circleci/config.yml, README.md, src/README.md, src/commands/README.md, src/examples/README.md, src/executors/README.md, src/jobs/README.md
=> Small fixes

src/jobs/push_build_to_bucket_job.yml
Add bucket_path param in push_build_to_bucket_job
=> Add bucket_path param in push_build_to_bucket_job (#10)[semver:minor]

src/jobs/README.md
=> Readme for push_build_to_bucket_job

src/commands/README.md, src/commands/build_push.yml, src/commands/deploy.yml, src/commands/maven_build_test.yml, src/commands/maven_cache_artifacts.yml, src/commands/maven_restore_artifacts.yml, src/commands/maven_save_output.yml, src/examples/java_monorepo_workflows.yml, src/examples/java_singleapprepo.yml, src/executors/maven_docker.yml, src/executors/maven_vm.yml, src/jobs/README.md, src/jobs/build_push_image.yml, src/jobs/deploy_job.yml, src/jobs/maven_build_test.yml, src/jobs/no_op.yml
fixes bug introduced in #17 
hardcode main steps, because steps-parameter defaults can not use parameter values themselfs; see also [here](https://discuss.circleci.com/t/cci-2-1-conditional-step-on-list-steps-parameter-type/28432/5)
=> Fix bug in ric-orb@v2.0.0

src/examples/java_monorepo_setup.yml, src/examples/java_monorepo_workflows.yml, src/examples/java_singleapprepo.yml
according to https://github.com/ricardo-ch/incidents-api/pull/179
=> fix example workflows

src/examples/java_monorepo_workflows.yml, src/examples/java_singleapprepo.yml, src/jobs/README.md, src/jobs/build_push_image.yml
because it makes builds more efficient and seems to not cost us anything https://circleci.com/pricing/#comparison-table
=> enable docker_layer_caching by default

src/examples/java_monorepo_setup.yml, src/examples/java_monorepo_workflows.yml, src/examples/java_singleapprepo.yml, src/jobs/maven_build_test.yml
login to jfrog so that maven build and test has access to required test-container images
unblocks https://github.com/ricardo-ch/selling-domain/pull/326
=> Improve maven build test job

README.md, src/examples/go_monorepo_workflows.yml, src/examples/go_singlerepo.yml, src/examples/java_monorepo_workflows.yml, src/examples/java_singleapprepo.yml, src/jobs/README.md, src/jobs/build_push_image.yml
latest changes on master https://github.com/ricardo-ch/ricardo-orbs/pull/30 are partially redundant with what you @alex-013 did for go-orb
i think this is the "correct" way to merge the 2 worlds and proceed
=> Resolve merge conflicts with master

src/examples/go_monorepo_workflows.yml
primarily because i forgot to [semver:patch] #32 🤦‍♂️ 🙈
=> tweak comment

src/commands/auth_gke.yml, src/commands/deploy.yml, src/examples/go_monorepo_workflows.yml, src/examples/go_singlerepo.yml, src/examples/java_monorepo_workflows.yml, src/examples/java_singleapprepo.yml, src/jobs/README.md, src/jobs/build_push_image.yml, src/jobs/deploy_job.yml
this is typically useful for apps with specific builds for primary/secondary, e.g. solr
example repo: https://github.com/ricardo-ch/search-data-importer-orders
=> parametrize isopod config filename

src/examples/README.md
like the title sais. and also i forgot to tag previous merge commit with version string so i need another commit to trigger new [semver:minor] release
=> add go-examples to readme

src/commands/README.md, src/commands/build_push.yml, src/commands/deploy.yml, src/commands/docker_build_push.yml, src/commands/gke_port_forward.yml, src/commands/install_build_test.yml, src/commands/maven_auth.yml, src/examples/README.md, src/examples/go_monorepo_workflows.yml, src/examples/go_singlerepo.yml, src/examples/java_monorepo_workflows.yml, src/examples/java_singleapprepo.yml, src/executors/README.md, src/jobs/README.md, src/jobs/build_push_image.yml, src/jobs/deploy_job.yml, src/jobs/docker_build_push.yml
as an alternative to isopod_build job, because sometimes we dont use isopod (e.g. search solr, which deploys a solr-plugin into a solr cluster)
=> add docker_build_push job

README.md, src/examples/go_monorepo_workflows.yml, src/examples/go_singlerepo.yml, src/examples/java_monorepo_workflows.yml, src/examples/java_singleapprepo.yml, src/executors/README.md, src/executors/maven_docker.yml, src/jobs/README.md, src/jobs/maven_build_test.yml, src/jobs/maven_deploy_artifact.yml
=> Revert "[semver:minor] Configurable executor"

.circleci/config.yml
=> update ssh key fingerprint

.circleci/config.yml, README.md
See updated [README](https://github.com/ricardo-ch/ricardo-orbs/blob/update_docs/README.md#how-to-set-up-publishing-in-circleci)
=> update docs on publishing orb

src/jobs/README.md, src/jobs/js_deploy_storybook.yml
Add a command to deploy storybook
=> add storybook deploy command

src/jobs/README.md
Try to deploy correctly https://github.com/ricardo-ch/ricardo-orbs/pull/69
=> [semver:minor] Deploy storybook job release

src/commands/docker_build_push.yml
tagging was broken, I'm not sure why this didn't pop-up earlier!?
=> fix tagging

src/commands/build_push.yml, src/commands/deploy.yml, src/jobs/build_push_image.yml, src/jobs/deploy_job.yml
Asana: https://app.asana.com/0/1134825272690689/1204470630366815/f
Adding image suffix for building image and deploy.
=> Image suffix

src/jobs/js_push_build_to_bucket_job.yml
=> use gcp alpine in js push-to-bucket

src/scripts/authenticate.sh
Edit authentication script to support GKE dev-banana
=> authenticate to dev-banana

src/examples/go_monorepo_workflows.yml, src/examples/go_singlerepo.yml, src/examples/java_monorepo_workflows.yml, src/examples/java_singleapprepo.yml
umbrella ticket https://github.com/ricardo-ch/compliance-orb/issues/22
=> remove deprecated compliance orb examples

src/scripts/authenticate.sh
Add authentication support for prod-tomato.
=> Prepare for new cluster migration
