- README.md
- src/commands/README.md
- src/commands/deploy.yml
As we already use mono repositories on github and also want to use them more often depending on the requirements, we need to have the possibility to define the isopod configuration file in the deploy command.
> Add deploy parameter to declare the isopod configuration file

- src/jobs/push_build_to_bucket_job.yml
Change push_build_to_bucket into job. Currently there is no need having it as command.
As a job, it will make apps' config files smaller.
> transform pushing to bucket into job

- src/executors/isopod.yml
- src/jobs/build_push_image.yml
- src/jobs/deploy_job.yml
- src/jobs/push_build_to_bucket_job.yml
Setting environment variable ISOPOD_VERSION as default for isopod version. 
It is set in CircleCI contexts: prod and dev to 0.24.0.
> default isopod version to env var ISOPOD_VERSION

- src/commands/maven_auth.yml
This fixes the issue `mkdir: cannot create directory ‘/home/********/.m2’: File exists`
> Fix mkdir for already existing .m2 dir

- src/executors/js.yml
- src/jobs/publish_npm_module_job.yml
Publish job was cp from working config in style-guide [here](https://github.com/ricardo-ch/style-guide-react/blob/c7444b350d9eec5a34ecc76f19e9e1855276416c/.circleci/config.yml#L196)
> publishing npm modules job & js executor

- src/@orb.yml
this should replace the useless example url [here](https://circleci.com/developer/orbs/orb/ricardo/ric-orb) with the actual link to this repository
> point to correct source repository

- src/jobs/quality_gate_jest_test_runner_job.yml
- src/jobs/quality_gate_js_runner_job.yml
Jobs for frontend quality gating
- `quality_gate_jest_test_runner_job.yml` - runs jest tests with CircleCi parallelism
- `quality_gate_js_runner_job.yml` - runs all other js tests, e.g. lint, ts
Both jobs are proved to be working in `marketplace-frontend-app` [dashoboard](https://app.circleci.com/pipelines/github/ricardo-ch/marketplace-frontend-app?branch=speedup-tests)
> test runner job for jest

- src/examples/java_monorepo_setup.yml
- src/examples/java_monorepo_workflows.yml
- src/examples/java_singleapprepo.yml
- src/examples/service_one.yml
- src/jobs/README.md
extend examples as sketched in https://github.com/ricardo-ch/incidents-api/pull/181
addresses this [slack discussion](https://ricardo-ch.slack.com/archives/C34DE9XQ8/p1658316530169269) regarding how to do github status checks on monorepos
goal is to have a designated job (name) for each app that is executed in every case, which allows github status check to work properly (note: it does not deal gracefully with "missing" jobs unfortunately)
---
personal concern:
what im really scared of is the coupling between github repo- / -branch config and circleCI-config, which is totally by custom convention (i.e. you 100% dont notice if you break it, and it might not even be visible on the branch/build because the change might introduce a regression that is only visible later when a single app is …
> adapt examples so that they support github status checks on monorepos

- README.md
- src/examples/java_monorepo_workflows.yml
- src/examples/java_singleapprepo.yml
- src/jobs/README.md
- src/jobs/build_push_image.yml
‼️ this is a breaking change ‼️ 
change the working directory of the build_push_image job (isopod) in case a submodule path is set.
the underlying assumption is that in the stereotypical case the path is a module directory containing the isopod file as well as the dockerfile, both of which agnostic to their nesting
advantage over current implementation:
- in case of monorepo, the docker build is executed from project root, thus the dockerfile must be path aware! with the new implementation the dockerfile can be agnostic because isopod works in that directory
> Change isopod working directory

- src/commands/README.md
- src/commands/maven_cache_artifacts.yml
- src/commands/maven_restore_artifacts.yml
- src/jobs/maven_build_test.yml
problem: if cache for cache-key exists, circleCI will not update the cache
- for classic repos this is fine: hash of pom is part of the cache-key, and we only need updates to .m2 if the pom changes, thus cache always contains all we need
- workflow for the single app in the repo
- restoring cache-key `prefix-{{hash "pom.xml"}}`
- building the single app
- caching `.m2`
- for mono-repos this is **problematic**: hash of pom is part of the cache-key, but cache is created with build of each individual module. since the modules are typically built individually, so the .m2 is often missing artifacts that are required for the other app(s).
- workflow for app1 in the monorepo
- restoring cache-key `prefix-{{hash "pom.xml"}}`
- building app1
- caching `.m2`
- workflow for app2 in the monorepo
- …
> fix cache key for maven artifact cache in case of monorepo

- src/jobs/docker_build_push.yml
fixes a bug from #42 
seems like you need to checkout before you restore workspace…
> fixing bug in docker-build-push job

- src/commands/js_restore_build_outputs.yml
- src/commands/js_save_build_outputs.yml
- src/jobs/push_build_to_bucket_job.yml
Introduce command for` persisting to workspace` and `attaching workspace` in a safe way, where data could be stored in separate folders  of workspace (beta or prod). This way we are sure that running 2 jobs in parallel, but for different contexts will not overwrite each others workspaces.
Use this new command in `push_build_to_bucket_job`.
> js - push_build_to_bucket_job changes

- src/commands/README.md
- src/commands/docker_build_push.yml
- src/commands/gke_port_forward.yml
- src/jobs/README.md
- src/jobs/docker_build_push.yml
- adding optional `local_port` option for `gke_port_forward`, this is needed because some flows port-forward to more than one service
- fixing bug in `docker_build_push`: it had image name hardcoded to `search-solr`
Example of usage:
- https://github.com/ricardo-ch/search-solr-admin/pull/48
> Adding local_port to port forward, fix missing image_name for docker_build

- README.md
- src/examples/go_monorepo_workflows.yml
- src/examples/go_singlerepo.yml
- src/examples/java_monorepo_workflows.yml
- src/examples/java_singleapprepo.yml
- src/executors/README.md
- src/executors/maven_docker.yml
- src/jobs/README.md
- src/jobs/maven_build_test.yml
- src/jobs/maven_deploy_artifact.yml
Adapts the `maven_build_test` and `maven_deploy_artifact` to use the `executor` type instead of a string, allowing to use custom executors for building.
> Configurable executor

- README.md
- src/examples/go_monorepo_workflows.yml
- src/examples/go_singlerepo.yml
- src/examples/java_monorepo_workflows.yml
- src/examples/java_singleapprepo.yml
- src/executors/README.md
- src/executors/maven_docker.yml
- src/jobs/README.md
- src/jobs/maven_build_test.yml
- src/jobs/maven_deploy_artifact.yml
Adapts the maven_build_test and maven_deploy_artifact to use the executor type instead of a string, allowing to use custom executors for building.
> Make executor configurable

- src/commands/README.md
- src/commands/remote_docker.yml
- src/jobs/README.md
- src/jobs/build_push_image.yml
- src/jobs/docker_build_push.yml
see [slack#this-thread](https://generalmarketplaces.slack.com/archives/C045RL4D25V/p1665994055865799)
and [slack#other-thread](https://generalmarketplaces.slack.com/archives/C043LTSQ535/p1665735292744169)
stop overwriting docker version for remote docker with something that is not always supported anymore by circleCI
> use circleCI's default docker version by default for remote-docker

- src/jobs/go_build_test.yml
this allows a build to use dockercompose/testcontainers if it wanted to do so
> login to docker registry for go-build-test

- src/commands/README.md
- src/commands/maven_cache_artifacts.yml
- src/jobs/maven_build_test.yml
- src/jobs/maven_deploy_artifact.yml
- We should only cache `.m2/repository` so that the settings.xml is not cache as it also contained the password.
- The cache restore was always overwriting the settings.xml, and therefore we changed the order (first restore cache, then load settings.xml from CircleCI env var), to support older caches that still contain settings.xml.
> Fix folder for maven cache

- src/commands/docker_build_push.yml
- src/executors/isopod.yml
- src/jobs/build_push_image.yml
- src/jobs/deploy_job.yml
- src/jobs/docker_build_push.yml
- src/jobs/go_build_test.yml
- src/jobs/maven_build_test.yml
- src/jobs/push_build_to_bucket_job.yml
these changes require the following environment variables in the context:
- GAR_APPLICATION_CREDENTIALS: [see 1password](https://start.1password.com/open/i?a=MSNVIFFLNRGSHOM4JGHI76MG6Y&v=cuv5v6wmn362r7i7lr2huklpre&i=2pgccgovd5dpjewpjsp7ddai5q&h=ricardo-ch.1password.com)
- DOCKER_GAR_REGISTRY_URL: `europe-west1-docker.pkg.dev`
- DOCKER_GAR_USERNAME: `_json_key_base64`
- DOCKER_GAR_PASSWORD: `<base64 encoded json key from above>`
- JFROG_ENABLED: `true`
- GAR_ENABLED: `true`
Once we've migrated we can simply remove the JFROG_ENABLED variable from the context to disable pushing to jfrog.
> add support for google artifact registry

- src/executors/isopod.yml
Use the virtual docker repository in us-east4 to reduce intercontinental egress costs (circleci is running everything in Northern Virgina).
This repository only contains isopod and platform-charts-deploy (the most used images in circleci)
> Use Virtual Repository in us-east4

- src/scripts/authenticate.sh
GOOGLE_APPLICATION_CREDENTIALS is required to create a new KMS client
> set default value for GOOGLE_APPLICATION_CREDENTIALS

- src/jobs/codeql.yml
- src/templates/codeql/codeql.conf
This fixes a bug where it was assumed a bin directory exists in the home directory of the user. This is the case for any of the provided circleci docker images, but not for most other ones.
We now always provide a configuration file for codeql. The default one is now part of this repository.
> Codeql fixes & improvements

- src/jobs/js_push_build_to_bucket_job.yml
stop using isopod executor in [src/jobs/js_push_build_to_bucket_job.yml](https://github.com/ricardo-ch/ricardo-orbs/pull/91/files#diff-2b0e22a058e164d0fb92b99feb62d1e1f32ce194bd7d3fa566ce66adf260dad9)
[slack](https://generalmarketplaces.slack.com/archives/C043LTSQ535/p1687339764349499)
[working execution](https://app.circleci.com/pipelines/github/ricardo-ch/marketplace-frontend-app/4484/workflows/55d3138f-2db0-43e8-b215-4d760a6a9d62/jobs/20609)
> use gcp public image in js push-to-bucket job

- src/jobs/js_publish_npm_module_job.yml
Change the way how we publish npm modules.
Now `js_publish_npm_module_job` requires` ci:prepublish` script to exist in package.json `scripts`.
This script need to copy `package.json` into build folder and ideally format it to have only publish essential information, for example we don't want to have devDependencies listed in published `package.json` file.
Good news is that with this PR we won't need to use `/build` as part of the path when importing some nested components
Proof that it works:
[style-guide-react PR](https://github.com/ricardo-ch/style-guide-react/pull/1409) and [marketplace-spa PR](https://github.com/ricardo-ch/marketplace-spa/pull/3288). You can compare locally in mspa that bundles came back to the same size as it was before [starting use gihub packages for …
> npm publish from build folder

- src/executors/js.yml
- src/jobs/js_build_job.yml
- src/jobs/js_deploy_storybook.yml
- src/jobs/js_install_dependencies_job.yml
- src/jobs/js_jest_runner_job.yml
- src/jobs/js_lint_runner_job.yml
- src/jobs/js_publish_npm_module_job.yml
- src/jobs/js_yarn_runner_job.yml
All jobs with js executor now accepts `node_version` optional parameter. The default value is now `lts`, so it will be a breaking change.
**SEMVER Update Type:**
**Closes Issues:**
-  ISSUE URL
> Add node version parameter for JS jobs

- src/executors/maven_vm.yml
(it should be a minor release)
Otherwise we always depend on the `current` tag of the Ubuntu image, that might change the default Java version under the hood.
See details in [thread](https://swissmarketplace.enterprise.slack.com/archives/C043ZRKHJ2Y/p1715165362105559)
> Add tag parameter for executor maven_vm

- src/scripts/authenticate.sh
Isopod requires the context name dev-cookie, while some other steps do not. For this reason, we pull dev-banana credentials and keep them locally under the names dev-cookie and dev-banana. This fix removes the need for changes in CICD pipelines after switching to dev-banana,
> adding two context names
